// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAynx-MH4MZqiFiZi4leio1jr4Ia70GImE',
    appId: '1:601945218136:web:d5f0b8afe9cca99bfcbe2d',
    messagingSenderId: '601945218136',
    projectId: 'tradetook-619be',
    authDomain: 'tradetook-619be.firebaseapp.com',
    databaseURL: 'https://tradetook-619be-default-rtdb.firebaseio.com',
    storageBucket: 'tradetook-619be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdtuT3TzHAnv75VF3aOqXxaDJ6ZEe7d7k',
    appId: '1:601945218136:android:e6001fb61787f4f8fcbe2d',
    messagingSenderId: '601945218136',
    projectId: 'tradetook-619be',
    databaseURL: 'https://tradetook-619be-default-rtdb.firebaseio.com',
    storageBucket: 'tradetook-619be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8loezUmKLAX__IvWCMSaWTNXXl5agTsI',
    appId: '1:601945218136:ios:a146710f6a8d75c3fcbe2d',
    messagingSenderId: '601945218136',
    projectId: 'tradetook-619be',
    databaseURL: 'https://tradetook-619be-default-rtdb.firebaseio.com',
    storageBucket: 'tradetook-619be.firebasestorage.app',
    iosBundleId: 'com.example.tradetook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8loezUmKLAX__IvWCMSaWTNXXl5agTsI',
    appId: '1:601945218136:ios:a146710f6a8d75c3fcbe2d',
    messagingSenderId: '601945218136',
    projectId: 'tradetook-619be',
    databaseURL: 'https://tradetook-619be-default-rtdb.firebaseio.com',
    storageBucket: 'tradetook-619be.firebasestorage.app',
    iosBundleId: 'com.example.tradetook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAynx-MH4MZqiFiZi4leio1jr4Ia70GImE',
    appId: '1:601945218136:web:56e7d57900a26f21fcbe2d',
    messagingSenderId: '601945218136',
    projectId: 'tradetook-619be',
    authDomain: 'tradetook-619be.firebaseapp.com',
    databaseURL: 'https://tradetook-619be-default-rtdb.firebaseio.com',
    storageBucket: 'tradetook-619be.firebasestorage.app',
  );

}